"""RAG Facile chat agent tools.

Each @tool is callable by the smolagents ToolCallingAgent during a chat session.
The workspace root is set once at session start by the agent harness.
"""

import subprocess
from pathlib import Path

from smolagents import tool


# Module-level workspace reference — set by the agent harness at session start.
_workspace_root: Path | None = None


def set_workspace_root(root: Path | None) -> None:
    """Register the workspace root so tools can locate project files."""
    global _workspace_root
    _workspace_root = root


@tool
def get_ragfacile_config() -> str:
    """Read the current ragfacile.toml configuration.

    Use this to answer questions about the RAG pipeline settings such as
    which preset is active, retrieval parameters, collection IDs, etc.
    """
    if _workspace_root is None:
        return (
            "No workspace detected — ragfacile.toml was not found in the current "
            "directory or any parent directory. "
            "Run 'rag-facile setup' to create a workspace."
        )
    config_file = _workspace_root / "ragfacile.toml"
    if not config_file.exists():
        return (
            "No ragfacile.toml found in this workspace. "
            "Run 'rag-facile setup' to create one."
        )
    return config_file.read_text(encoding="utf-8")


@tool
def get_agents_md() -> str:
    """Read AGENTS.md from the workspace — the project architecture guide.

    Use this to answer questions about the project structure, available packages,
    CLI commands, coding conventions, or how the RAG pipeline is organised.
    """
    if _workspace_root is None:
        return "No workspace detected. Run 'rag-facile setup' to create a workspace."
    agents_file = _workspace_root / "AGENTS.md"
    if not agents_file.exists():
        return (
            "No AGENTS.md found in this workspace. "
            "This file is generated by 'rag-facile setup' and describes the project "
            "architecture. It may be missing if the workspace was created manually."
        )
    return agents_file.read_text(encoding="utf-8")


@tool
def get_recent_git_activity() -> str:
    """Show the last 10 git commits in the workspace.

    Use this to answer questions about what changed recently, what the user
    has been working on, or whether the project is up to date.
    """
    if _workspace_root is None:
        return "No workspace detected. Run 'rag-facile setup' to create a workspace."
    try:
        result = subprocess.run(
            [
                "git",
                "log",
                "--oneline",
                "--decorate",
                "--no-merges",
                "-15",
            ],
            cwd=_workspace_root,
            capture_output=True,
            text=True,
            check=True,
        )
        output = result.stdout.strip()
        return output if output else "No commits found in this repository yet."
    except FileNotFoundError:
        return "git is not installed or not available on PATH."
    except subprocess.CalledProcessError as exc:
        return f"git log failed: {exc.stderr.strip()}"
